### ISSUE TITLE
Documentation Needed: Exporting Data

### ISSUE THREAD

**Issue by siedentop** [plausible/docs#1]
Many thanks for plausible. I just converted to an annual subscription :) 

I am missing documentation on how to export data.

Specifically the two types:

1. The page views per day. This can be exported to CSV with the little "download" icon in the main graph. (Feedback: I found it hard to find this button.) [This link][1] does answer the question, but it is not in the "docs" for plausible.
2. How to export raw data, incl. referrers, country, etc.

Best regards, Christoph

[1]: https://plausible.nolt.io/45

**Comment by ukutaht** [comment]
Thanks for the suggestions.

We don't have support for raw data export (yet). However, I do agree that we should document the download button that allows you to download daily visitor numbers.

**Comment by metmarkosaric** [comment]
Thanks for the feedback! I've now added the instructions on [how to export the data](https://docs.plausible.io/export-stats/).
