### ISSUE TITLE
Does Cloudfront subdirectory require Lambda Edge?

### ISSUE THREAD

**Issue by iHiD** [plausible/docs#100]
Hello. Thanks for the new instructions for Cloudfront proxying. 

They say 
> In case of a subdirectory installation, you'll also need to add a data-api attribute to tell the script where the data should be sent.

My understanding of Cloudfront is that it does not strip matching paths when proxying. So if I have a subdirectory of `subdirectory`[1], this would proxy to plausible as `plausible.io/subdirectory/js/script.js`, which I believe is incorrect. I believe a Lambda-Edge component is required for this. My suspicion is that the extra sentence was added to the docs without considering this, and that the author doesn't use a subdirectory. But my understanding might be incorrect and I wanted to check before I invested the time into the Lambda-Edge. 

[Here](https://stackoverflow.com/questions/31567994/multiple-cloudfront-origins-with-behavior-path-redirection) is a StackOverflow question that I think is relevant.

Your advice would be appreciated :)

[1]  (e.g. `<script defer data-domain="yourdomain.com" data-api="/subdirectory/api/event" src="/subdirectory/js/script.js"></script>`)

**Comment by iHiD** [comment]
I've now built a Lambda Edge to do this, and have a working Cloudfront deployment through Terraform. I'll upload it publicly tomorrow so others can use it as a reference 🙂

**Comment by ukutaht** [comment]
Amazing @iHiD this would be very helpful for our docs

**Comment by iHiD** [comment]
For anyone else coming across this, this works if you want to use Cloudfront on a subdirectory. 

This is the Lambda function:
- https://github.com/exercism/terraform/tree/main/terraform/lambda_functions/plausible

This is the terraform that links it together (should be pretty readable if you're clicking in the console, not using terraform too)
https://github.com/exercism/terraform/blob/main/terraform/webservers/cloudfront_webservers.tf#L59-L130

I'll write it up at some stage, but I don't have time right now :)

**Comment by metmarkosaric** [comment]
thank you @iHiD!
