### ISSUE TITLE
LICENSE of this repository?

### ISSUE THREAD

**Issue by bhavin192** [plausible/docs#102]
I wanted to use the files given on the https://plausible.io/docs/excluding-localstorage page. So, I came here to check license of this repository. It will be good to have some license to this documentation repository, or explicitly mention the license of the HTML and CSS files given on the above page.

**Comment by ukutaht** [comment]
That makes sense. Which license would you recommend for documentation? I think I've seen a lot of Creative Commons in this space but a quick search also brings up [GFDL](https://en.wikipedia.org/wiki/GNU_Free_Documentation_License)

**Comment by bhavin192** [comment]
Correct. I have mostly seen CC-BY-SA for docs and MIT for the code snippet from docs. I not that familiar with GNU FDL, although I have seen it in some projects. I will try to spend time and understand it.

**Comment by bhavin192** [comment]
Found this:

> Attribution - any copy of a work licensed under the GFDL must include a full copy of the license. That's not a big burden in software, but if someone is printing off a GFDL document, they are legally obliged to include a license printout which may be as long as the document. The CC-by-sa is much simpler, requiring attribution as requested by the source, which typically is the source's name (e.g. "Practical Action," "Appropedia" or "Jodie Smith"), perhaps a title, and a link.

https://wiki.creativecommons.org/wiki/GFDL_versus_CC-by-sa 
A note from the above page:
> NOTE: This is an adaptation from an email (7 March 2012) and needs to be thoroughly fact-checked, and have unfair aspects removed. It's written from a pro CC-by-sa perspective and might be unfair to the GFDL.

https://en.wikipedia.org/wiki/Wikipedia:Comparison_of_GFDL_and_CC_BY-SA

> Copyleft – any changes/derivative works must be available under the same terms. However, the 2 licences are not compatible with each other, so GFDL text cannot be put inside a CC BY-SA document unless it is used under the fair use doctrine. 

This one was interesting one. Prevents others from including text from docs in their work, unless that work is also GFDL, I guess. Otherwise, GFDL seems to be fine, and I think one can have GFDL code in their website or code.

**Comment by ukutaht** [comment]
Thanks for the research @bhavin192.

I don't think our documentation is as sensitive as the code so a permissive Creative Commons license should suffice. Unless you have any objections @metmarkosaric? You've written most of the docs :)

**Comment by metmarkosaric** [comment]
Is there a license that requires you to link back to the original source? I'm not sure in which cases people would want to copy our docs but it may give us a potential issue with SEO etc so the ideal would be that any copy links back to the original

**Comment by ukutaht** [comment]
Seems like the Creative Commons license achieves that. From the [license text](https://creativecommons.org/licenses/by-sa/4.0/legalcode)

> If You Share the Licensed Material (including in modified form), You must:
>     retain the following if it is supplied by the Licensor with the Licensed Material:
>         identification of the creator(s) of the Licensed Material and any others designated to receive attribution, in any reasonable manner requested by the Licensor (including by pseudonym if designated);
>         a copyright notice;
>         a notice that refers to this Public License;
>         a notice that refers to the disclaimer of warranties;
>         a URI or hyperlink to the Licensed Material to the extent reasonably practicable;

Last line being the relevant.

**Comment by metmarkosaric** [comment]
That sounds good to me!

**Comment by ukutaht** [comment]
@bhavin192 done! https://github.com/plausible/docs/commit/3511da0bc99fdfd2c13301ae6ec4d3f41f0b63f0
