### ISSUE TITLE
How to exclude on a custom domain?

### ISSUE THREAD

**Issue by garrison** [plausible/docs#11]
The page at https://docs.plausible.io/excluding#block-the-plausible-analytics-script-on-your-domain provides instructions for excluding oneself from analytics using uBlock origin.  However, in my experience this is not working for sites which have been set up using a custom domain following https://docs.plausible.io/custom-domain.  I have also tried the obvious variation `domain.org plausible_subdomain.domain.org * block`, but this does not seem to work either.

I believe the instructions should be updated to include how to do this properly.  If, for whatever reason, the instructions ought to work and my experience is user error, I would claim that it should be stated explicitly in the documentation that the same procedure should work for custom domains, as well.

**Comment by metmarkosaric** [comment]
Good point @garrison! I've added the info on custom domains.

I've just tested this on my end (on both Firefox and Chromium) and it works on my site (ms.markosaric.com is my own chosen subdomain):

markosaric.com ms.markosaric.com * block

Could you please try again?

Do make sure to tick the "I am an advanced user" box in uBlock Origin like explained as I've seen that being an issue before.

When I visit my site now, this is how I see the block in uBlock Origin in Chromium:

![Screenshot from 2020-08-07 16-39-50](https://user-images.githubusercontent.com/34340819/89656999-b59b4000-d8cc-11ea-829f-b7639ff5f69e.png)

And in Firefox:

![Screenshot from 2020-08-07 16-39-30](https://user-images.githubusercontent.com/34340819/89657000-b6cc6d00-d8cc-11ea-9dc0-d7f96cf29552.png)

**Comment by garrison** [comment]
> Do make sure to tick the "I am an advanced user" box in uBlock Origin like explained as I've seen that being an issue before.

This was indeed the problem.  Before I was confused because my other sites (without a custom domain) had the Plausible script blocked successfully, so I assumed I must be adding the custom rules properly.  But this was a wrong assumption, as I now believe that uBlock Origin was blocking these trackers because it blocks `plausible.io` by default.

**Comment by metmarkosaric** [comment]
Good to hear that worked! Enjoy Plausible!
