### ISSUE TITLE
Cloudflare proxy example doesn't cache the /js/script.js file because Netlify origin returns cache-control: max-age=0

### ISSUE THREAD

**Issue by jobsort** [plausible/docs#110]
I've just integrated Plausible on [Jobsort.com](https://www.jobsort.com/) and got an alert from SEMrush that I'm serving uncached JS files which was surprising.

The example to create a Cloudflare worker from https://plausible.io/docs/proxy/guides/cloudflare#step-1-create-a-worker doesn't cache anything even though `caches.default.put` is used. If you look at the Cloudflare documentation https://developers.cloudflare.com/workers/learning/how-the-cache-works#cache-api they say:

> Explicitly store a response in the cache using caches.default.put(..) and explicitly delete caches.default.delete(..). For example, say your origin is returning max-age:0 and you can’t figure out how to change that header at your origin. You can explicitly tell Cloudflare to cache this response by setting cache-control: max-age=1000 on the response passed into cache.put().

The Plausible origin returns `cache-control: max-age=0` and in fact the cache is not used at all if using the documented example, as seen in the screenshot:

<img width="472" alt="image" src="https://user-images.githubusercontent.com/79706640/125494760-48e0abfe-ebfa-4dd6-9726-dfdddf26e39c.png">

So, the example code from https://plausible.io/docs/proxy/guides/cloudflare#step-1-create-a-worker should be changed from:

```
async function getScript(event, extensions) {
    let response = await caches.default.match(event.request);
    if (!response) {
        response = await fetch("https://plausible.io/js/plausible." + extensions.join("."));
        event.waitUntil(caches.default.put(event.request, response.clone()));
    }
    return response;
}
```

to:

```
async function getScript(event, extensions) {
    let response = await caches.default.match(event.request);
    if (!response) {
        response = await fetch("https://plausible.io/js/plausible." + extensions.join("."));

      const cacheableResponse = new Response(response.body, response);

      // Must explicitly add cache age because the origin serves `max-age=0`.
      cacheableResponse.headers.set("cache-control", "max-age=31536000");

      event.waitUntil(caches.default.put(event.request, cacheableResponse.clone()));

      return cacheableResponse;
    }
    return response;
}
```

With the fix, the response is now cached:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/79706640/125504652-45163249-2347-4df5-94b0-e1f34abb2c29.png">

The latency of serving the script file drops from ~400ms to ~40ms.

Question is, what's the story behind versioning the script if it actually gets cached with the above fix?
Also, why is Netlify configured to not allow client to cache the Plausible JS script? Thanks

**Comment by ukutaht** [comment]
Thanks for the investigation.

For more context around why the cache headers are as they are, see https://github.com/plausible/analytics/issues/1085 and [this thread on Netlify's forum](https://answers.netlify.com/t/solved-error-500-for-some-redirects-post/38312). Specifically, [this post](https://answers.netlify.com/t/solved-error-500-for-some-redirects-post/38312/6?u=ukutaht) a support engineer from Netlify.

We used to set a cache expiry but for some reason that I don't understand, it causes Netlify to return 500 response sometimes. It's very weird and I'm not happy about it. We have other reasons to change our setup as well. Hopefully soon we can enable the cache headers again on the script. Sorry about that.

Adding cache headers after the response has cleared Netlify's servers should be fine. I think your suggestion makes sense and we should incorporate it into the guide. I think 1 year is too long though. I would expire the cache much sooner, like 1 day.

**Comment by jobsort** [comment]
@ukutaht I tend to agree with you about the TTL being less than 1 year but Lighthouse, if I remember correctly, will complain otherwise. My recommendation is to come up with a versioning system so that you can cache it for one year.

**Comment by ukutaht** [comment]
>  My recommendation is to come up with a versioning system so that you can cache it for one year.

How would that work? I'm familiar with adding the hash to the filename or something like that to bust the cache but that only works reasonably well if the `<script>` tags are auto-generated and deployed often.

Are you suggesting our users would put a versioned filename on their site e.g:
```html
<script src="https://plausible.io/js/plausible-v1.js></script>`
```

And when we release an update, they would have to manually re-deploy with a new filename to get the update?

```html
<script src="https://plausible.io/js/plausible-v2.js></script>`
```

**Comment by jobsort** [comment]
Yes, that's exactly what I had in mind :) The API endpoint would potentially have to be versioned as well.

**Comment by ukutaht** [comment]
Right, I see. I don't think we'll make that the default because most analytics users lean heavily towards convenience over performance and we're trying to strike a balance there. 

I think our default should be to have a non-versioned file caches for something like a day or a week. That should be perfectly fine when it comes to web performance.

I can see us providing a versioned file with an indefinite cache expiry for those who want to opt into it.

**Comment by metmarkosaric** [comment]
Our script is now being cached so there should not be a need for this anymore
