### ISSUE TITLE
SMTP SSL Configuration needs clarity

### ISSUE THREAD

**Issue by navjotjsingh** [plausible/docs#115]
On this page

https://plausible.io/docs/self-hosting-configuration

the default value of `SMTP_HOST_SSL_ENABLED` is mentioned as `false`. Which leads a person to believe that he needs to set the value as `true` for SSL to work. Which turned out to be wrong.

You need to set its value as `1` and not `true` to get the mails working. This needs to be clarified in the docs.

**Comment by mir1198yusuf** [comment]
@navjotjsingh i am getting error and not able to send any email 
`Connecting to aspmx.l.google.com [2404:6800:4003:c1c::1b]:25 ... failed: Cannot assign requested address`

**Comment by ruslandoga** [comment]
👋 @navjotjsingh 

Self-hosted docs are in the process of being moved to https://github.com/plausible/community-edition

I've created https://github.com/plausible/community-edition/issues/95 to keep to keep track of your issue :)

Sorry for a late reply!
