### ISSUE TITLE
Can't make it work with NuxtJS

### ISSUE THREAD

**Issue by hvitis** [plausible/docs#118]
Hello!

I have tried all official docs for nuxtjs and vue-meta, tried different combinations. Could you tell me where exactly I would need to attach the script? Before body tag? After? In the footer maybe? Thank you.

**Comment by metmarkosaric** [comment]
hello @hvitis! perhaps these instructions can help? https://debbie.codes/blog/nuxt-analytics

**Comment by hvitis** [comment]
Thanks for quick reply! Not at all but an interesting blog. Thanks for sharing.

My problem was that nuxt has an option to add src files
```
Head:[src: LINK_TO_FILE, body; true]
```
What I did (dummy me) was I pasted whole line with the script as a link which resulted in something like:
```
<script src="<script src='plausible.jsx>"/>
```

**Comment by ukutaht** [comment]
@hvitis Did you manage to fix the issue?

**Comment by hvitis** [comment]
> @hvitis Did you manage to fix the issue?

Yes. As stated above. Fully my fault. Thank you! Please close the issue.
