### ISSUE TITLE
Search Console integration no longer working

### ISSUE THREAD

**Issue by tcurdt** [plausible/docs#119]
I noticed that integration was working but now was broken. I disconnected the account and started again

![Screen Shot 2021-08-26 at 23 45 42](https://user-images.githubusercontent.com/13697/131040616-98d1c874-0673-433c-8a07-5e7ab6757197.png)

Clicking on "Continue with Google" gives an error

```
Error 401: deleted_client
The OAuth client was deleted.
```

but I haven't changed anything in the console and it should be still setup correctly.

**Comment by jesperordrup** [comment]
Is this still the status? 

When I try to connect I get 

![image](https://user-images.githubusercontent.com/3120151/235507766-2996049d-7c21-4460-866f-e8f2bbd45b6e.png)

What Ive done:

Followed the guide: https://plausible.io/docs/google-search-console-integration
Added the clientId and secret
doublechecked domain 1
