### ISSUE TITLE
Uncached JavaScript and CSS files

### ISSUE THREAD

**Issue by SimonKlausLudwig** [plausible/docs#121]
Semrush reports uncached Javascript for https://plausible.io/js/plausible.js which pull down the SEO Score.

**Comment by ukutaht** [comment]
Thanks for reporting. This is a known issue caused by us being on Netlify. We'll fix it when we move to another CDN.

**Comment by SimonKlausLudwig** [comment]
Thanks, when do you think will you move to another CDN. Are there any plans yet ?

**Comment by metmarkosaric** [comment]
Uku can comment on the CDN. I just wanted to note that the fact that our script is uncached doesn't mean that this will affect your SEO negatively despite what SEMRush score says. Our script is quick to load, lightweight and optimized for performance and it won't have any negative impact on your SEO.

**Comment by ukutaht** [comment]
> Thanks, when do you think will you move to another CDN. Are there any plans yet ?

Yeah, planning to do it by the end of the year

**Comment by metmarkosaric** [comment]
Our script is now being cached so there should not be any reports from Semrush anymore
