### ISSUE TITLE
Feature Request: View multiple properties in goal conversions

### ISSUE THREAD

**Issue by Wolfkhan66** [plausible/docs#139]
When viewing goal conversion stats it appears to only be possible to breakdown by 1 property at a time. Ideally i would like to be able to view all at once or at the minimum 2 at a time.

**Comment by Wolfkhan66** [comment]
Any update on the progress of this.
I recently tried to query what I needed from the stats API only to discover it also has the same issue of only being able to query 1 property at a time.

**Comment by metmarkosaric** [comment]
Sorry, no update on this. We are a small team with limited development resources so need to focus on most frequently requested features first. You can follow the progress on this in this thread: https://github.com/plausible/analytics/discussions/846

**Comment by Wolfkhan66** [comment]
Would it be possible then to return an id on results requested via the api so it would then be possible to make queries on different properties and combine locally?

**Comment by ukutaht** [comment]
@Wolfkhan66 do you have an example? I don't fully understand your request
