### ISSUE TITLE
Looking for a "0% cookie 100% privacy" branding/ribbon ?

### ISSUE THREAD

**Issue by divinerites** [plausible/docs#15]
I was looking for adding a "ribbon" of some sort for my site now fully without cookie (thanks to plausible :-)
but I couldn't find anything close to this "0% cookie 100% privacy" sort of.

May be with the need for more privacy/cookie free sites, it would be a good opportunity to reach/lead such a privacy "brand" ?

Any idea/inside/thought/link for this ??

**Comment by metmarkosaric** [comment]
Thanks, would be nice to have for sure! Just need to find a design(er)! There's another thread on this topic (https://github.com/plausible/analytics/issues/107) so I'll close this one for now.
