### ISSUE TITLE
Vercel proxy documentation

### ISSUE THREAD

**Issue by Styren** [plausible/docs#168]
The documentation for [proxying through nextjs/vercel](https://plausible.io/docs/proxy/guides/nextjs) only covers nextjs however vercel supports a range of different frameworks.

Would it be possible to expand the docs a bit on how to proxy plausible through vercel for other frameworks, for example with a react SPA? Happy to put a PR on it if anyone can give some guidance. Otherwise I'd recommend removing "Vercel" from the title as the instructions work for any nextjs deployment.

**Comment by metmarkosaric** [comment]
thanks for the feedback @styren! these are community contributed instructions so we don't have any further details unfortunately. perhaps our [npm package](https://github.com/plausible/plausible-tracker) would be an easier way to do this for you?

**Comment by davestewart** [comment]
See #170

**Comment by metmarkosaric** [comment]
There is a new set of instructions for Vercel now thanks to @davestewart : https://plausible.io/docs/proxy/guides/vercel
