### ISSUE TITLE
Vercel setup

### ISSUE THREAD

**Issue by davestewart** [plausible/docs#169]
Hello,

I integrated the proxy for a static site (i.e. not Next) on Vercel yesterday.

It's a bit different as it uses a `vercel.json` file.
 
Do you want me to submit a new page to the [docs](https://plausible.io/docs/proxy/introduction)?

**Comment by metmarkosaric** [comment]
hello @davestewart! there was [a question](https://github.com/plausible/docs/issues/168) about this recently so would be great with some instructions. thanks!

**Comment by davestewart** [comment]
No problem!

For anyone reading this before I get round to it; it's just a single JSON file in your repo's root:

```json5
// /vercel.json
{
  "rewrites": [
    {
      "source": "/stats/js/script.js",
      "destination": "https://plausible.io/js/plausible.js"
    },
    {
      "source": "/stats/api/event",
      "destination": "https://plausible.io/api/event"
    }
  ]
}
```

I prefixed the `source` paths with `/stats` as I wanted to be able to filter in the devtools.

**Comment by davestewart** [comment]
@metmarkosaric - a question.

On the [docs](https://plausible.io/docs/proxy/introduction) page, the platform list is shown as so:

![image](https://user-images.githubusercontent.com/132681/148815412-1c5c71c8-797e-43b6-8cbb-b52edea93789.png)

Note that the entry for "Next.JS / Vercel" is irregular, as the rest of the entries are `<platform>` whereas this is `<framework> / <platform>`.

As such, I don't know whether to:

1. add an additional page, and an additional list entry of the same (irregular) format:

    - Vercel / SPA
    - Vercel / Next.JS
    
2. rename the page and entry to just "Vercel", matching the regular format of the other entries, and update the page to include instructions for both SPA and Next.js:

    - Vercel

3. add an additional page, but in a subfolder, so the top level list format is again regular (I presume this will also affect the side menu):

    - Vercel
        - SPA
        - Next.js    


I don't know enough about Next.js to know if `<framework> / <platform>` is the right format, as in, in Vercel the only place Next can be hosted? Or, if the `<platform>` is the proper top-level organisational approach.

Option 2 seems like the best one I think.

If you let me know what you would prefer, I'll knock it out now.

PS. Not sure if you are concerned with SEO implications of the page URL changing?

**Comment by davestewart** [comment]
I've started on the combined approach, and I think it's probably the right one, as actually there's lots of commonality between the two approaches.

Thinking this will be the best structure:

- Intro
- SPA config
- Next.js config
- Script

**Comment by metmarkosaric** [comment]
sounds good to me! do not change the URL itself please but feel free to change the headline. thanks!

**Comment by davestewart** [comment]
OK. The URL will point to https://plausible.io/docs/proxy/guides/nextjs even though the page will actually be Vercel.

**Comment by metmarkosaric** [comment]
perfect!

**Comment by davestewart** [comment]
OK... change of mind / plan.

I've dug more into this whole setup and it seems this page is actually just a summary of the package `next-plausible` and that package offers much more functionality to manage tracking, etc.

Reviewing the Vercel docs, it seems because Vercel have a special interest in Next, that the configuration can get quite granular:

- https://nextjs.org/docs/api-reference/next.config.js/redirects

As the basic static site setup seems much simpler...

- https://vercel.com/docs/cli#project-configuration/rewrites

...and I'm not a React / Next guy, and there are concerns around URLs, I've written a much simpler, standalone page for just a basic Vercel app setup.

I have also sent a support request to Vercel, so hopefully they can clarify if the basic JSON can also be used for Next sites:

> Hi there,
> 
> I'm helping out Plausible.io with some updated documentation for proxying calls to their analytics service:
> 
> - https://github.com/plausible/docs/issues/169
> 
> The documentation I am going to write concerns proxying a static app using your `vercel.json` project configuration and rewrites:
> 
> - https://vercel.com/docs/cli#project-configuration/rewrites
> 
> I have this set up and working just fine.
> 
> However, Plausible have an existing documentation section which concerns redirecting using Next.js, and uses a 3rd party library. 
> 
> The setup seems more complex than just using the JSON setup, and there is also a Vercel docs page which goes into much greated detail:
> 
> - https://nextjs.org/docs/api-reference/next.config.js/rewrites
> 
> So (finally!) my question is, do Next apps HAVE to be set up in this way (using JavaScript and plugins) or can they just use the `vercel.json` approach, which seems much easier and quicker?
> 
> Thanks,
> Dave 

This keeps the docs flexible for both now and in the future.

PR should be ready by the time you read this :)

**Comment by metmarkosaric** [comment]
great, thank you @davestewart!
