### ISSUE TITLE
Netlify redirect rules need to use status 200 instead of 202

### ISSUE THREAD

**Issue by JohannesRudolph** [plausible/docs#177]
I setup my netlify redirect/proxy rules as documented here https://github.com/plausible/docs/blob/master/docs/proxy/guides/netlify.md#step-1-add-url-rewrite-rules

My site has a custom 404.html page. Whenever sending a request to `/api/event`, the redirect rule did not get executed, instead I got served the 404.html page. 

I noticed that the netlify docs are never mentioning 202 as a supported status code for proxying. Thus changing the redirect rule to use status code 200 and that fixed the redirect, which is now properly proxying to plausible.

**Comment by ftes** [comment]
Can confirm that `202` does not work, but `200` does work.

**Comment by ukutaht** [comment]
Thank you
