### ISSUE TITLE
Can't get maxmind to work

### ISSUE THREAD

**Issue by mbouclas** [plausible/docs#232]
Followed the docs here [https://plausible.io/docs/self-hosting#1-maxmind-geolocation-database](url) but it doesn't seem to work. The map is never populated and the countries tab shows `No data yet`.
* Added the Maxmind credentials in the `geoip/geoip.conf`
* Added the conf variable `GEOLITE2_COUNTRY_DB=/geoip/GeoLite2-Country.mmdb`
* started the stack using `docker-compose -f docker-compose.yml -f geoip/docker-compose.geoip.yml up -d`
* checked the docker logs for any possible errors, but nothing there

Any ideas?

**Comment by metmarkosaric** [comment]
hi @mbouclas! this is a repo for our docs where we do improvements to the instructions and guides etc. for help with your self-hosted installation please post in our self-hosted community forum and hopefully a community member who's had the same problem can help you out: https://github.com/plausible/analytics/discussions/categories/self-hosted-support. thanks!
