### ISSUE TITLE
List all configuration options

### ISSUE THREAD

**Issue by shyim** [plausible/docs#25]
Like Google Integration. 

I have no glue how this will be fetched from env https://github.com/plausible/analytics/blob/ead4a7d56099c9b0a63dcc574b3a7c889a862366/lib/plausible/google/api.ex#L143

**Comment by metmarkosaric** [comment]
We have the Google Search Console integration as documented here: https://docs.plausible.io/google-search-console-integration/

You can see an example on our live demo: https://plausible.io/plausible.io?period=30d&source=Google

Did you have any specific questions in mind?

**Comment by shyim** [comment]
It was `GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET` (https://github.com/plausible/analytics/blob/ead4a7d56099c9b0a63dcc574b3a7c889a862366/config/config.exs#L140-L141)

I mean this page https://docs.plausible.io/self-hosting-configuration

**Comment by metmarkosaric** [comment]
One Plausible user has now contributed with instructions on how to enable Search Console on Self-Hosted. Take a look here: https://docs.plausible.io/self-hosting-configuration#google-search-integration
