### ISSUE TITLE
Unreleased feature already in docs

### ISSUE THREAD

**Issue by lucasra1** [plausible/docs#259]
I wanted to use this [feature](https://plausible.io/docs/file-downloads-tracking) with my self-hosted plausible instance. It wasn't working so I checked the repo. [Here](https://github.com/plausible/analytics/blob/ce461b51927370ab0032769be2850a8c37574a71/CHANGELOG.md?plain=1#L9) I found, that this feature is in the "unreleased" section. A bit confusing maybe.

**Comment by RobertJoonas** [comment]
Thanks for reaching out @lucasra1!

We keep our docs up to date with the cloud version of Plausible. Self-hosted is not updated as frequently as the managed hosting version which changes daily. Think of it as a long term release to help us and help you not need to upgrade things all the time and risk breaking stuff. We stack all the new features and fixes that have been battle tested on the hosted version and release a new self-hosted release twice a year. You can learn more here: https://plausible.io/blog/building-open-source

Hope this makes sense!
