### ISSUE TITLE
Can't use file-downloads script along with manual scripts

### ISSUE THREAD

**Issue by naustra** [plausible/docs#265]
I made changes to my plausible configuration to be able to use custom location along with file-downloads and outbound-links.

Everything is ok for outbound-links but I can't trigger file-downloads event when I download pdf on my website.

Is there something, I'm missing ?

**Comment by ukutaht** [comment]
Are you using Plausible Cloud or self-hosted?

**Comment by metmarkosaric** [comment]
This issue tracker is for our documentation so I'm closing this. Please find help for your self-hosted installation [here](https://github.com/plausible/analytics/discussions/categories/self-hosted-support) or [contact our customer support](https://plausible.io/contact) if this question is about Plausible cloud.
