### ISSUE TITLE
Event Triggers via Tag Attribute

### ISSUE THREAD

**Issue by MentalGear** [plausible/docs#275]
Just went over your guide, and I was surprised and somewhat disappointed that you don't feature a quick and easy way to track an event via simple attribute addition, for example:

```html
<button data-pa-event="downloadClicked"> Download </button>
```

PS: You could transform the attr name (via npm package) or on-page load if you fear ad-blocking.

**Comment by RobertJoonas** [comment]
Thanks for your feedback @MentalGear! We keep the issue tracker for actual bugs rather than feature requests. Closing this, as I've moved this discussion to https://github.com/plausible/analytics/discussions/2237 where I've also responded.
