### ISSUE TITLE
docs.plausible.io no longer redirects to plausible.io/docs

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/docs#289]
We used to have all docs.plausible.io pages redirect to plausible.io/docs pages but this is no longer happening. We still use many of the old docs.plausible.io links around the site plus there's SEO value in those old URLs. Is there a way to return the redirect?

Here's what happens now: https://docs.plausible.io/self-hosting
While it used to 301 redirect automatically to: https://plausible.io/docs/self-hosting

@plausible/developers

**Comment by ukutaht** [comment]
@cnkk I screwed this up in Netlify but that's a bad way to do it in the first place. Could we direct docs.plausible.io to our current infra and add a redirect in the Caddy/Haproxy config? Then this redirect would be in our IaC repos which would be an improvement

**Comment by metmarkosaric** [comment]
@cnkk any update on this? we're still getting reports of broken links around the site

**Comment by metmarkosaric** [comment]
one subscriber just reported that it's been fixed now - thanks!
