### ISSUE TITLE
Sphinx extension

### ISSUE THREAD

**Issue by rkdarst** [plausible/docs#294]
I've made a Sphinx extension for Plausible:
https://pypi.org/project/sphinx-plausible/

The existing instructions are more complex than they need to be, Sphinx has the ability to make an extension to insert custom scripts into the head with the required tags.  Thus, this works for any theme with no modification.  Reviews of the code welcome, it is very new!

By the way, do you know if `<script defer="defer" ...>` is equivalent to `<script defer ...>` in all practical cases?  Only newer sphinx can do the second, but if I use the first, then I can make it support very old Sphinx versions, too.

**Comment by metmarkosaric** [comment]
thanks for your contribution @rkdarst!

> do you know if <script defer="defer" ...> is equivalent to <script defer ...> in all practical cases?

from what i can see, it is equivalent 

when everything is ready from your side, feel free to add this integration to our integrations list: https://plausible.io/docs/integration-guides

thanks again!

**Comment by rkdarst** [comment]
I'm sorry for being a bit too late, but I found there was an even simpler way to do this, that doesn't even need an extension and also works with any theme:

Add the following to your `conf.py` file:

```python
html_js_files = [
    ('https://plausible.io/js/script.js', {"data-domain": "yourdomain.com", "defer": "defer"}),
]
```

(unfortunately I've been busy so haven't been able to post this here, but last thing I did was test that his works)

**Comment by metmarkosaric** [comment]
np! it's on https://plausible.io/docs/integration-guides now
