### ISSUE TITLE
nginx caches plausible.io IP when domain is used directly in proxy_pass

### ISSUE THREAD

**Issue by envy** [plausible/docs#328]
Hi,

we deployed a plausible proxy which worked at first but broke two weeks later.

Turns out that nginx resolves plausible.io once on start and then uses that IP until it's restarted.

This is bad since you run behind a CDN.

We changed our config like this to force nginx to respect DNS TTLs:

```
    # Setting a variable forces nginx to resolve and respect DNS TTLs
    set $plausible "plausible.io";
    # Set to your own DNS resolver
    resolver 127.0.0.11 ipv6=off;

    location ~ ^/js/(.*)$ {
        proxy_pass https://$plausible/js/$1;
        proxy_set_header Host plausible.io;

        proxy_buffering on;
    }

    location = /api/event {
        proxy_pass https://$plausible/api/event;
        proxy_set_header Host plausible.io;
        proxy_buffering on;
        proxy_http_version 1.1;

        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
    }
```

Of course the resolver IP needs to be changed to the local environment and also IPv6 can be enabled if available.
We also proxy every request to `/js/*` since we need the other scripts you offer.

Maybe you can incorporate this into your documentation.

**Comment by cnkk** [comment]
We have updated the config (https://github.com/plausible/docs/commit/0eb9d1e1743127fae4d4ef1b0b25a6b15a0e2360) to fix the DNS lookup problem.
