### ISSUE TITLE
Self-hosted JS snippet has no port 8000 in URL

### ISSUE THREAD

**Issue by TheCrowned** [plausible/docs#331]
I am struggling to get Plausible running locally, and I believe the javascript snippet we get to paste before `</head>` is wrong. Currently, it is this
```javascript
<script defer data-domain="localhost" src="http://localhost/js/script.js"></script>
```
but `script.js` does not exist at that location, since Plausible will run on port 8000 by default.

**Comment by metmarkosaric** [comment]
hi @TheCrowned! this place is only for making specific changes to our documentation so I'll close your thread. we have a self-hosted community forum that you can post and get help by other members of our community here: https://github.com/plausible/analytics/discussions/categories/self-hosted-support. thanks!

**Comment by ukutaht** [comment]
@TheCrowned Running on localhost outside of development and testing has never been considered as a use-case. I'm struggling to understand why you would want to run it this way. Why are you running Plausible on localhost instead of a DNS-configured hostname?

**Comment by TheCrowned** [comment]
Thanks for replying @ukutaht. In this case it was indeed testing, and localhost was the quickest. But would it make a difference if it were a DNS-configured hostname? :thinking: Even if it were 
```javascript
<script defer data-domain="localhost" src="http://example.com/js/script.js"></script>
```
, and Plausible listens on port 8000 by default, that would still be wrong. That is, unless running on a DNS-configured hostname results in a different snippet being produced. I would find that even more unexpected though, since technically there is no difference between `localhost` and `example.com`: they are both hostnames.

**Comment by ukutaht** [comment]
Our docker-compose file maps port 8000 to 80. Many people also run SSL proxies in front which make it accessible on port 443. In the vast majority of cases, the app is running on port 8000 but via the internet it's accessible on port 80 or 443.

Since the app is not aware of which proxies run in front of it, it would be incorrect to add port 8000 into the URL.

**Comment by TheCrowned** [comment]
> Our docker-compose file maps port 8000 to 80

[Does it](https://github.com/plausible/hosting/blob/master/docker-compose.yml#L37)? :thinking:  I am not a docker expert, so feel free to close if I am wrong.

**Comment by TheCrowned** [comment]
> Could you open an issue on the plausible/hosting repo

I had done it, but it was converted into a _Discussion_ (not by me) 
https://github.com/plausible/analytics/discussions/2522

**Comment by ukutaht** [comment]
This is the right place for issues regarding self-hosted setup: https://github.com/plausible/hosting
