### ISSUE TITLE
Integration: Material for MkDocs

### ISSUE THREAD

**Issue by notpushkin** [plausible/docs#339]
Hey! I've implemented an integration for [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/): https://material-plausible-plugin.ale.sh/

I can't come up with an introduction text for https://plausible.io/docs/integration-guides though. Could you help?

**Comment by metmarkosaric** [comment]
thanks very much for your contribution @notpushkin! I've just added it to our integrations list!
