### ISSUE TITLE
Provide easy code examples for popular custom events

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/docs#34]
To make it easy for those without JavaScript experience or without any development help to set up goals:

Text link clicks
Button clicks 
Form submits

**Comment by underthecocotree** [comment]
Relates to: https://github.com/plausible/docs/pull/75

For pure buttons that are not part of a form there might need to be some amendments to the code.

**Comment by metmarkosaric** [comment]
thank you @underthecocotree!
