### ISSUE TITLE
Explain referal in "404 error pages tracking"

### ISSUE THREAD

**Issue by NiklasBr** [plausible/docs#353]
We have [this](https://plausible.io/docs/error-pages-tracking-404) up and running but have yet to figure out where to view the referal source in the dashboard. The data sent from the client to plausible.io looks like this:

```json
{"n":"404","u":"https://example.com/404","d":null,"r":"https://example.com/dokumenter","w":1358,"p":{"path":"/404"}}
```

So, we would love to configure the dashboard to also show the `r` value, in this case `https://example.com/dokumenter`.

**Comment by metmarkosaric** [comment]
hi @NiklasBr! it should work out of the box with the instructions we provided. i use the exact same method as described on my site and you click on 404 in the goals section for referral sources to be shown in the Top Sources. see https://plausible.io/markosaric.com?goal=404

**Comment by metmarkosaric** [comment]
do contact [our customer support](https://plausible.io/contact) if you have any more questions about this please. i'll close this as this repo we use for changes to our docs only
