### ISSUE TITLE
Adblockers: Note about Subdomains + Adblockers

### ISSUE THREAD

**Issue by tajacks** [plausible/docs#358]
I checked the docs for a note on this, as I recently encountered it, but I did not find it. 

While I was setting up my self-hosted solution, and investigating why the script was being blocked even on a domain I owened, I realized that by default uBlock Origin (from the easyPrivacy filter list) blocks the following pattern:

```
://stats.*/script.js`
```

When I was installing my self-hosted solution, I originally chose `stats.mydomain.tld` as the entrypoint for plausible. This made sense for me due to the nature of it and surely others may have a similar line of thinking. Unsure on which section it fits best in (Adblock/Proxy or Self-hosted) but I believe the docs would benefit from a note warning users about choosing an inconspicuous subdomain.

**Comment by tajacks** [comment]
Here is an example of how this wording could look: 

https://github.com/plausible/docs/pull/359

**Comment by metmarkosaric** [comment]
thanks @tajacks! we already mention something like it in the instructions: Do avoid words like 'plausible', 'analytics', 'tracking', 'stats', etc. as they may be blocked.
