### ISSUE TITLE
Can I force light mode on shared dashboard?

### ISSUE THREAD

**Issue by BernhardBaumrock** [plausible/docs#366]
I've developed a module to integrate the plausible dashboard into the ProcessWire CMS: https://processwire.com/talk/topic/27322-rockanalytics-gdpr-compliant-google-analytics-alternative-for-processwire/

Now the problem is that the dashboard shows up in dark mode if the user's operating system is set to dark mode: ![img](https://i.imgur.com/vU84tsK.png)

Can I prevent that somehow or could you add a feature to support ?mode=light in the dashboard url?

Also I'm not sure why the dashboard shows up in full width now. In an older version it has some space to the left and right:

<img width="1651" alt="image" src="https://user-images.githubusercontent.com/8488586/224773727-0dccabc0-7a09-4596-ab62-01d29a6e1e7c.png">

Thx for your help!

**Comment by metmarkosaric** [comment]
thanks for reaching out @BernhardBaumrock!

you can change the color https://plausible.io/docs/embed-dashboard#2-generate-the-embed-code

and you can also change the width: https://plausible.io/docs/embed-dashboard#manual-width-mode
