### ISSUE TITLE
Average visit duration when queried per page reported via API differs from one in UI

### ISSUE THREAD

**Issue by huksley** [plausible/docs#379]
Hi, I am using cloud version and query API using /aggregate API call, e.g.

```js
const period = "month";
const id = "z-WeukB91Zws";
const stats = await fetch("https://plausible.io/api/v1/stats/aggregate?" +
  new URLSearchParams({
    site_id,
    period,
    filters: "event:page==/v/" + id,
    metrics: "visitors,pageviews,bounce_rate,visit_duration,events",
  }),
  {
    headers: {
      Authorization: `Bearer ${plausibleKey}`,
    },
  }
)
  .then(okstatus)
  .then((res) => res.json());
console.info(stats);
```

Output result is
```js
{
  results: {
    bounce_rate: { value: 0 },
    events: { value: 136 },
    pageviews: { value: 7 },
    visit_duration: { value: 2086 },
    visitors: { value: 4 }
  }
}
```

Documentation [states](https://plausible.io/docs/stats-api#metrics), visit_duration is in seconds, so it it 34 minutes?!

But in the UI it is more realistic (3m 48s)
<img width="863" alt="image" src="https://user-images.githubusercontent.com/1594349/227777149-0fc4f437-59fa-43a7-ae6b-dc30b6b57dda.png">

My goal is to get statistics per `/v/ID` page on visits and custom goal execution (AddComment, Like, etc.). Is the API can be used for that?

**Comment by metmarkosaric** [comment]
thanks for reporting @huksley! we actually don't have time on page in the stats api at this time. what you're looking at is visit duration which is a different metric from time on page. we'd like to introduce time on page in the stats api in the future. there's a thread for this feature request here: https://github.com/plausible/analytics/discussions/2727. i'm closing this as we keep the github issues for actual changes to our docs. thanks!
