### ISSUE TITLE
Tracking page view via anchors instead of path

### ISSUE THREAD

**Issue by hottehead** [plausible/docs#38]
Hey,

i have a website built with a template that uses anchors ```'#about-me'``` for page navigation. Plausible now only tracks ```'/'``` as a page view. Can I somehow change it to evaluate anchors as page view?

**Comment by metmarkosaric** [comment]
Hey! Have you tried our hash based script instead of the default one? It should work for your site. See https://docs.plausible.io/hash-based-routing

**Comment by hottehead** [comment]
Thanks a lot. Should have RTFM myself xD

And thanks for this awesome piece of software.

**Comment by hottehead** [comment]
Pages are now tracked like this ```/#about-me?src=test-src```. The query params are also used. And there is no source tracked in ```Top Sources```. This time I read [this manual](https://docs.plausible.io/manual-link-tagging) and tried all combinations.

**Comment by metmarkosaric** [comment]
Hmm you see no sources at all? The referral sources are counted only when they start a new session on your site so it is expected that any other "internal" source should not be counted. The advice is that UTM tags etc should not be used for internal links, only for links on external sources that don't normally send a referral header such as social media, paid advertising campaigns etc.

**Comment by hottehead** [comment]
I tried visiting my page in firefox private mode to force the start of a new session. I always put the link into the browser by hand to mimic the link opening via i.e. an email. I then tried all combinations from the docs, see the following top page trackings. But no source was tracked. How can I verify a new session was started for plausible?
```
/
/#about-me
/#about-me?source=test
/#about-me?ref=test-ref
/#about-me?utm_medium=social-paid&utm_source=facebook&utm_campaign=black-friday-sale
```

**Comment by metmarkosaric** [comment]
You cannot use a private mode with Plausible as we don't count stats using cookies. Try a different browser or a different IP address instead. Or as a first visit on a new day. Or share the exact links with me and I'll click on them so you can check.

**Comment by hottehead** [comment]
*dough*  Im really sorry for being so stupid with the private mode and cookies... And thanks a lot for responding lightning fast!

Everything works as expected! I am very pleased to have an open source, well done, GDPR compliant tracker!

Do you have a donation option? I am running plausible self-hosted and do not have a subscription, so I'd like to donate you guys some bucks.

**Comment by metmarkosaric** [comment]
You're welcome! And yes, we do have a donation option. See: https://github.com/sponsors/plausible
