### ISSUE TITLE
What's the API to list sites

### ISSUE THREAD

**Issue by goenning** [plausible/docs#394]
I found the docs for the API to get a site by id `https://plausible.io/api/v1/sites/abc.com`, but what's the API to get the list of sites that I have access to?

Edit: I tried `https://plausible.io/api/v1/sites` but that returns 404

**Comment by goenning** [comment]
For reference, something like Fathom has https://usefathom.com/api#list-sites

This would enable better integrations as I could show users a list of users they have instead of asking them to enter the website domain

**Comment by metmarkosaric** [comment]
thanks for the feedback @goenning! we don't have an API to list all sites at the moment unfortunately. you can see what our sites API does here: https://plausible.io/docs/sites-api. 

i'll close this as we keep this section for docs improvements and not for feature discussions. there's already a thread for discussing the idea of an API that lists all sites here: https://github.com/plausible/analytics/discussions/1280
