### ISSUE TITLE
Docker Secrets support is undocumented

### ISSUE THREAD

**Issue by mark-monteiro** [plausible/docs#398]
I found the following issue in the main repo that added support for using Docker secrets for any config variable: https://github.com/plausible/analytics/issues/1105

This functionality doesn't appear to be documented anywhere, and also takes a different approach to using Docker secrets than I have seen commonly used in other popular Docker images (i.e. adding separate `_FILE` environment variables to specify a path to load the secret from).

From what I can tell, Plausible will load any config variable from the config directory (defaults to /run/secrets) when there is a file with a name matching the variable. This should be added as a note somewhere in the docs, and should probably also encouraged to be used for sensitive variables (DATABASE_URL, GOOGLE_CLIENT_SECRET, etc)

**Comment by ruslandoga** [comment]
👋 @mark-monteiro  

Self-hosted docs are in the process of being moved to https://github.com/plausible/community-edition

I referenced your issue in https://github.com/plausible/community-edition/issues/97

Sorry for a late reply!
