### ISSUE TITLE
[DOC] give a warning for CSP headers when using subdomain

### ISSUE THREAD

**Issue by divinerites** [plausible/docs#4]
This issues is backport from https://github.com/plausible/analytics/issues/251 . Much better place for this.

When your site is using some Content Security Policy, you have to add plausible.io in order the .js to load and to work. I guess this is known if you manage your website's header with CSP.

But when you add statsforplausible.mydomain.com in order to go thru Adblock problems, do not forget to add this subdomain specifically to your CSP too.

May be you can add a small warning in the setup documentation page ? I didn't made a doc PR because i do not know your policy for that :-)
HTH.

**Comment by metmarkosaric** [comment]
Thanks! I've added a quick note about [this here](https://docs.plausible.io/custom-domain/#replace-the-tracking-code-on-your-website-with-the-new-code).
