### ISSUE TITLE
New session

### ISSUE THREAD

**Issue by bsthomsen** [plausible/docs#408]
Hey I'm looking to see if plausible could be used for a POS solution. Basically, the main problem is that the solution, will run on a screen 16 hours a day, without ever being refreshed/reloaded. Therefore we would need to manually trigger "new visitor". When the screen has timed out and a new user comes up and starts interacting with the screen.

Any help on if it's possible to manually trigger a new session? Like GA3 had the session_start event. That would trigger a new "session/visitor". I've skimmed through the docs but it doesn't seem like there much information, on advance usage like this.

**Comment by metmarkosaric** [comment]
hi @bsthomsen! you wrote this on our github for docs where we keep track of changes to our documentation. the best place for questions is [our customer support](https://plausible.io/contact). please do email us with more details on what you're trying to do and we'll see what can be done. thanks!
