### ISSUE TITLE
Auto Height for iframe embed?

### ISSUE THREAD

**Issue by vegastriguy** [plausible/docs#423]
I am somewhat a newb with plausible but I am in love!🤓

For my own daily persusal, I created a scrolling page on my main company website to review about 25 of the 75 websites I host in WP Bakery individual rows....that way I can provide a quick screen grab as needed.  When plausible generates the standard iframe embed code the default height is 1600px which was ok, until I learned how to update all my scripts with ////// script.file-downloads.outbound-links.js and so now I have two goals...I went through and manually changed all these embeds to 2200px...I guess it is what it is...but, maybe I could add some css that would somehow make that iframe to 100% height with maybe 25px of padding?  Any ideas....?  No bigs....but, just the neat and tidy coming out in me...hahahahahahh

**Comment by ruslandoga** [comment]
👋 @vegastriguy 

Self-hosted docs are in the process of being moved to https://github.com/plausible/community-edition

If your feature request is still relevant please open an issue on https://github.com/plausible/community-edition/issues

Sorry for a late reply!
