### ISSUE TITLE
Add Custom Event Goals example for ahref

### ISSUE THREAD

**Issue by warpling** [plausible/docs#43]
I want to try Custom Goals for the links on my landing page but don't know the best practices for this kind of thing (If I did maybe I could add an example). How does this seem?

```html
<head>
<script async defer data-domain="[MY_DOMAIN]" src="https://plausible.io/js/plausible.js"></script>
<script>
  window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }

  function OpenLink(self, e, name) {
    e.preventDefault();
    plausible(name)
    var href = $(self).attr("href");
    window.open(href);
    return false;
}
</script>
</head>

<body>
    <a href="https://plausible.com" onclick="return OpenLink(this, event, 'Test Event');">
</body>
```

**Comment by metmarkosaric** [comment]
Thanks @warpling! Perhaps you could try with these instructions? For best accuracy, add target="_blank" to open the tracked links in new window https://docs.plausible.io/internal-link-click-tracking/

**Comment by warpling** [comment]
hmm yeah my solution above isn't reporting any events for some reason. Setting the _blank target seems to help. Any idea why this is?

**Comment by metmarkosaric** [comment]
From my understanding it's less accurate as the script doesn't get to fire. It does so when the click opens a new window. This is also why we didn't publicly publish the instructions I sent earlier. That method can be used and works aright if you need to track internal clicks but we plan at some point in the future to develop and share a better method.

**Comment by warpling** [comment]
Ah okay, I didn't understand and thought I could use this for tracking external links. I'll restore the old generic Plausible code for doing that!
