### ISSUE TITLE
Question on alternative to proxy approach for JS script

### ISSUE THREAD

**Issue by donohoe** [plausible/docs#433]
I'm using the Plausible service and I would like to host the script locally in order to reduce the missed numbers from ad-blockers. Under normal circumstances I'd use the [WP plugin for Plausible or other methods](https://plausible.io/docs/proxy/introduction) and be done with it but thats not an option here for *reasons*.

Outside of the approaches offered I'm looking to do it a different way and I just wanted to check if my assumptions are correct.

**Question:**

- If I make a local copy of `plausible.io/js/script.js`, host it at, `mysite.com/js/script.js` it should "just work"? 
- And if so, I just need to pull down the latest on a regular basis to capture any changes?
- - Assuming yes, any rough estimate on how often the scripts change (should this be daily, weekly, etc)?

Thanks.

**Comment by metmarkosaric** [comment]
hi @donohoe! both of those assumptions should be correct. and the script doesn't change that often. there's the history of changes here https://github.com/plausible/analytics/commits/master/tracker/src/plausible.js
