### ISSUE TITLE
Comparsion is only in the graph, missing from all boxes below

### ISSUE THREAD

**Issue by Megamannen** [plausible/docs#453]
When doing a comparison I expect do get double columns on all boxes (including Goals) to be able to compare those numbers as well

Right now it's only in the graph

![image](https://github.com/plausible/docs/assets/19424456/2748e31f-7b35-4f7b-b09d-f0ba8e2ee7de)

**Comment by metmarkosaric** [comment]
thanks @Megamannen! that's correct. there's a feature request for what you'd like to see here https://feedback.plausible.io/211
