### ISSUE TITLE
Custom events without having to manually add in console

### ISSUE THREAD

**Issue by mir1198yusuf** [plausible/docs#466]
To start with Plausible, want to use along with GA side by side.
A central place is a generic function which takes input as event name, json payload and fires GA event
In that same function, want to add the event triggering logic for Plausible.

Existing GA events could me many in number and is difficult to add each in console first as doc says that custom events have to be first configured in console https://plausible.io/docs/img/add-custom-event-goal.png

Any easy way to bypass this ? I want a solution that just by adding `plausible('CustomEventName', {props: {...customKeys}})` alongside GA trigger function , Plausible should start. working without much efforts

**Comment by metmarkosaric** [comment]
thanks @mir1198yusuf! you wrote this in our docs repo where we keep track of edits to the documentation. for any type of feature requests or ideas for improvements, here's the link to our feedback board https://feedback.plausible.io
