### ISSUE TITLE
Modsecurity trigger on text/plain please add description to whitelist Plausible in modsecurity.

### ISSUE THREAD

**Issue by PetervdPerk** [plausible/docs#469]
As described in plausible/analytics#3390 Plausible has a good reason to use `text/plain` over `application/json`.
However using `text/plain` causes modsecurity trigger when using self-host.
```
---FjqV3YIf---F--
HTTP/2.0 202
Server: nginx
Date: Sat, 17 Feb 2024 10:55:55 GMT
access-control-expose-headers:
Content-Length: 2
Content-Type: text/plain; charset=utf-8
access-control-allow-origin: *
x-request-id: F7ShKNTJEuNNNvQAAAJj
Connection: close
access-control-allow-credentials: true
cache-control: max-age=0, private, must-revalidate

---FjqV3YIf---H--
ModSecurity: Warning. Matched "Operator `PmFromFile' with parameter `userdata_wl_content_type' against variable `TX:0' (Value: `text/plain' ) [file "/etc/nginx/modsecurity.d/rules/comodo_free/10_HTTP_HTTP.conf"] [line "16"] [id "210710"] [rev "5"] [msg "COMODO WAF: Request content type is not allowed by policy. Please update file userdata_wl_content_type.||x.x.nl|F|2"] [data "TX:0=text/plain"] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [tag "CWAF"] [tag "HTTP"] [hostname "x"] [uri "/api/event"] [unique_id "170816735538.147102"] [ref "v0,4o0,10o0,10v351,10"]
```

A suggestion would to add a subchapter in the Plausible docs to add `text/plain` to the `userdata_wl_content_type` file.

**Comment by ruslandoga** [comment]
👋 @PetervdPerk 

Self-hosted docs are in the process of being moved to https://github.com/plausible/community-edition

Would you be able to make a relevant change in https://github.com/plausible/community-edition/blob/v2.0.0/reverse-proxy/apache2/plausible.conf? I don't use Apache myself so I'm not sure if I'd get it right :)

Sorry for a late reply!

**Comment by 2803media** [comment]
> As described in [plausible/analytics#3390](https://github.com/plausible/analytics/issues/3390) Plausible has a good reason to use `text/plain` over `application/json`. However using `text/plain` causes modsecurity trigger when using self-host.
> 
> ```
> ---FjqV3YIf---F--
> HTTP/2.0 202
> Server: nginx
> Date: Sat, 17 Feb 2024 10:55:55 GMT
> access-control-expose-headers:
> Content-Length: 2
> Content-Type: text/plain; charset=utf-8
> access-control-allow-origin: *
> x-request-id: F7ShKNTJEuNNNvQAAAJj
> Connection: close
> access-control-allow-credentials: true
> cache-control: max-age=0, private, must-revalidate
> 
> ---FjqV3YIf---H--
> ModSecurity: Warning. Matched "Operator `PmFromFile' with parameter `userdata_wl_content_type' against variable `TX:0' (Value: `text/plain' ) [file "/etc/nginx/modsecurity.d/rules/comodo_free/10_HTTP_HTTP.conf"] [line "16"] [id "210710"] [rev "5"] [msg "COMODO WAF: Request content type is not allowed by policy. Please update file userdata_wl_content_type.||x.x.nl|F|2"] [data "TX:0=text/plain"] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [tag "CWAF"] [tag "HTTP"] [hostname "x"] [uri "/api/event"] [unique_id "170816735538.147102"] [ref "v0,4o0,10o0,10v351,10"]
> ```
> 
> A suggestion would to add a subchapter in the Plausible docs to add `text/plain` to the `userdata_wl_content_type` file.

Finally how do manage this modsecurity problem (I have the same) tx

**Comment by PetervdPerk** [comment]
> Finally how do manage this modsecurity problem (I have the same) tx

That was an workaround that didn't work that well, rules get updated automatically thus needed manual intervention each time.
Since this issue was closed so quickly I presume that the developers just don't care about this issue, apparantly apache doesn't get used a lot....
