### ISSUE TITLE
Manual width mode does not work

### ISSUE THREAD

**Issue by thelfensdrfer** [plausible/docs#470]
The manual width mode described here: https://plausible.io/docs/embed-dashboard#manual-width-mode does not work for me. The container still contains the `max-w-screen-xl` class.

![image](https://github.com/plausible/docs/assets/699106/5392820a-ae83-4231-b0fe-e673bf447ea3)

The complete URL is: `https://****/share/****?auth=****&embed=true&theme=light&background=%23ffffff&width=manual`

I am using the latest plausible/analytics:v2.0 docker image.

**Comment by ruslandoga** [comment]
👋 @thelfensdrfer 

This seems more like a bug with Plausible rather than a documentation issue. I'll look into it!

**Comment by thelfensdrfer** [comment]
Whoops, didn't realize I was in the docs repository. Thanks!

**Comment by ruslandoga** [comment]
https://github.com/plausible/analytics/pull/3910 should fix this
