### ISSUE TITLE
Missing plausible-conf example file

### ISSUE THREAD

**Issue by abjoseph** [plausible/docs#48]
The **plausible-conf.env** file is missing from the self-hosted setup docs.

Docs page --> https://plausible.io/docs/self-hosting#1-clone-the-hosting-repo

Url with the below 404 --> https://plausible.io/self-hosting-configuration

![image](https://user-images.githubusercontent.com/26844547/103156122-7e420880-4773-11eb-8ac9-750c8bd29140.png)

**Comment by vuongtrunghieu** [comment]
The file itself is in [plausible/hosting](https://github.com/plausible/hosting) repo.
The new link for the docs is here: https://plausible.io/docs/self-hosting-configuration, or you can just click on the link next to Getting Started under Self-Hosting section on side menu.

You can see also: #47
