### ISSUE TITLE
Outbound link tracking JS "blocks" other event listeners on <a>

### ISSUE THREAD

**Issue by reinder42** [plausible/docs#49]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
I'm using [https://plausible.io/js/plausible.outbound-links.js](https://plausible.io/js/plausible.outbound-links.js) to track outbound clicks on links with Plausible. This script appears to send a request to Plausible prior to directing the user to the link which was clicked (a sensible approach). This broke checkout on a landing page though, because the checkout links also uses document.location to redirect the user to checkout (after obtaining a checkout session asynchronously). It's an edge case; the checkout link goes through a subdomain. I don't think there's a better way to do this, because both event listeners on the <a> tag are needed but do 'compete' with each other.

**Expected behavior**
I think this behavior should be noted/explained in [the docs](https://plausible.io/docs/outbound-link-click-tracking), so people are aware if they also have their own event listeners on <a> tags. An additional alternative for the docs, would be to provide 1-2 examples of sending the same outbound click tracking request using vanilla JS or jQuery. (This is what I'll end up using, i.e. adding the same functionality in an existing script + excluding checkout links.)

**Environment (If applicable):** (Occurred on, but not limited to)
 - OS: macOS Big Sur
 - Browser Safari 14.0.1

**Comment by reinder42** [comment]
Quick update here – I ended up solving this differently. I'm using the default Plausible JS, and then fire a `plausible("Outbound Link: Click", { props: { url: ... } });` directly in 'onclick' on the link. Outbound links open in a new window anyway, so the async request to Plausible is not interrupted. I don't think a documentation change is necessary, because sending custom events is already documented.

Cheers!
—Reinder

**Comment by metmarkosaric** [comment]
Sounds good @reinder42! And thanks for the update! I'll close this one.
