### ISSUE TITLE
Add link to https://plausible.io/docs in Repo's About Section

### ISSUE THREAD

**Issue by ACPK** [plausible/docs#50]
Thank you for putting the docs together. What are your thoughts on adding a link to https://plausible.io/docs?

<img width="1377" alt="Screen Shot 2021-01-07 at 7 07 21 PM" src="https://user-images.githubusercontent.com/2019893/103958760-d5ed5600-511b-11eb-8544-49d9a1d65d60.png">

**Comment by metmarkosaric** [comment]
done! thanks @ACPK!
