### ISSUE TITLE
/path/* filter broken

### ISSUE THREAD

**Issue by mquandalle** [plausible/docs#511]
Hello,

It's normally possible to filter using the `*` operator to match a set of pages. But it is currently broken on the hosted version of plausible.com. It was working yesterday so it seems the bug was introduced recently.

Example of the issue: https://plausible.io/mesaidesvelo.fr?filters=((is,entry_page,(/ville/*)))

**Comment by metmarkosaric** [comment]
thanks for reporting @mquandalle! could you please try to use the "contains" option? that allows you just to type the keyword without needing any `*` operator. here's the link: https://plausible.io/mesaidesvelo.fr?filters=((contains,entry_page,(/ville/)))

**Comment by mquandalle** [comment]
Yes it works with "contains"

**Comment by metmarkosaric** [comment]
thanks for the update! 

btw you wrote this in our GitHub for docs where we keep track of changes to our documentation pages. for the future, best place to report any type of issues with your account/dashboard is [our support](https://plausible.io/contact). thanks!
