### ISSUE TITLE
Example for workaround when event function does not work

### ISSUE THREAD

**Issue by rjgamer** [plausible/docs#68]
Hi guys,

uBlock origin is blocking plausible within firefox. No problem, but it would be cool if you could provide a fallback for the event function to get the callback triggered too.

https://plausible.io/docs/custom-event-goals

What you think about this?

```
<script async defer data-domain="<yourdomain.com>" src="https://plausible.io/js/plausible.js"></script>
<script>window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }</script>

```
How can the last line be rewritten, so the callback get be triggered too?

**Comment by ukutaht** [comment]
There's a code example of how we make sure the callback is triggered on our registration form:

```javascript
registerForm.addEventListener('submit', function(e) {
  e.preventDefault();
  setTimeout(submitForm, 1000);
  var formSubmitted = false;

  function submitForm() {
    if (!formSubmitted) {
      formSubmitted = true;
      registerForm.submit();
    }
  }

  plausible('Signup', {callback: submitForm});
})
```

I know it's not ideal but currently clients can work around the issue. We should revamp the API to make these kinds of things much simpler though.

**Comment by rjgamer** [comment]
Thanks for your response. 

Sure you have a fallback for the plausible function, written in the 2nd script-tag. But the callback for submitForm in your example does not get called, when the plausible.js isn't loaded respectively is blocked bei uBlock Origin in Firefox. 

The fallback in the 2nd script-tag needs to be rewritten, so a callback get called too. I think something like this:
```
<script>
window.plausible = window.plausible || function(name, args) { 
   if ('callback' in args) {
      args.callback();
   }
}
</script>
```

**Comment by ukutaht** [comment]
> But the callback for submitForm in your example does not get called, when the plausible.js isn't loaded respectively is blocked bei uBlock Origin in Firefox.

Yes it does get called. That's what the `setTimeout` is for. If the callback has not been triggered after 1 second, we ditch the analytics request and let the client move on. The whole point of this code snippet is to solve your problem precisely.

Your suggestion makse sense and it would need some work, currently it will call the callback unconditionally every time. It should only be called if the 'normal' callback flow fails. I agree with your suggestion but like I said it can be worked around for the time being.

When I touch that code next time we will probably add support for `navigator.sendBeacon` which will make the whole flow completely different.

**Comment by rjgamer** [comment]
Oh, you are right. But a little crunchy with setTimeout :) 

I will close this issue and be curious what you will bring with navigator.sendBeacon. 

Best regards.
