### ISSUE TITLE
improve steps for google search integration

### ISSUE THREAD

**Issue by whysthatso** [plausible/docs#70]
i've been trying to figure out via [this chapter](https://plausible.io/docs/self-hosting-configuration#google-search-integration) how to add that particular integration, but have been frankly overwhelmed by the google dev console.

maybe it's possible to add a step by step guide here, in order to help through the myriade of options in the dev console.

**Comment by metmarkosaric** [comment]
there's a step by step guide now thanks to @fanatiicx
