### ISSUE TITLE
Add a "forum" link to discourse / docs / landing page

### ISSUE THREAD

**Issue by divinerites** [plausible/docs#8]
It should be favorable to help people navigate between the community forum : discourse and 

- the documentation : doc
- the plausible dashboard
- the landing page

by adding similar links beside each other :

- add `Forum` link beside `Github` on `docs.plausible.io/`
- add `Forum` link beside `Docs`  on my Dashbord page `plausible.io/my_plausible_name`
- add `Forum` link beside `Docs` on `plausible.io` landing page
- add `Docs` (*and may be `my dashbord` ? not sure*) links on `plausible.discourse.group`

[EDIT] changed name to `forum` to be in phase with the site vocabulary.

**Comment by metmarkosaric** [comment]
Thanks @divinerites! 

* Added the link to the forum into the docs footer for now.
* We'll add it to the main site footer too when we do the upcoming update. 
* The dashboard page header will be completely changed as we're working on a new design. 
* Discourse plan we're on doesn't allow us to use multiple plugins so we've gone for the design one for now.
